apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: lab
data:
  # alert.rules: |-
  #   groups:
  #   - name: ops-forum-api
  #     rules:
  #     - alert: 'QUEBRA DE SLO'
  #       expr: (histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{job="app-forum-api",uri!="/actuator/prometheus"}[1m])) by (le))) >= 0.5
  #       for: 1m
  #       labels:
  #         app: 'api-forum-alura'
  #         severity: 'critical'
  #         group: 'ops-forum-api'
  #         env: 'production'
  #       annotations:
  #         title: 'QUEBRA DE SLO'
  #         summary: '90% das requisições estão sendo atendidas a 500ms ou mais.'
  #         description: 'API forum esta quebrando o SLO, 90% das requisições estão sendo atendidas em 500ms ou mais no último minuto.'

  #   - alert: 'ERRO 500'
  #     expr: (sum(rate(http_server_requests_seconds_count{job="app-forum-api", status="500", uri!="/actuator/prometheus"}[1m]))/sum(rate(http_server_requests_seconds_count{job="app-forum-api", uri!="/actuator/prometheus"}[1m]))) >= 0.01
  #     for: 1m
  #     labels:
  #       app: 'api-forum-alura'
  #       severity: 'critical'
  #       group: 'ops-forum-api'
  #       env: 'production'
  #     annotations:
  #       title: 'ERRO 500'
  #       summary: 'Erro 500 acima de 1% no último minuto.'
  #       description: 'API forum esta com taxa de erros 500 esta acima de 1% no último minuto'
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    rule_files:
      - alert.rules

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager-forum-api:9093

    scrape_configs:
    - job_name: prometheus-forum-api
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /actuator/prometheus
      scheme: http
      static_configs:
      - targets:
        - prometheus-forum-api:9090
    - job_name: app-forum-api
      metrics_path: /actuator/prometheus
      static_configs:
      - targets:
        - app-forum-api:8080    
 
