apiVersion: v1
kind: Service
metadata:
  name: prometheus-forum-api
  namespace: lab
spec:
  selector:
    app: prometheus
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 9090
  type: LoadBalancer