apiVersion: v1
kind: Service
metadata:
  name: prometheus-forum-api
  namespace: lab
spec:
  ports:
  - name: prometheus-forum-api
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: LoadBalancer
  selector:
    app: prometheus  