apiVersion: v1
kind: Service
metadata:
  name: alertmanager-forum-api
  namespace: lab
spec:
  ports:
  - name: alertmanager-forum-api
    port: 9093
    protocol: TCP
    targetPort: 9093
  type: LoadBalancer
  selector:
    app: alertmanager 