apiVersion: v1
kind: Service
metadata:
  name: prometheus-forum-api
  namespace: lab
spec:
  selector:
    app: prometheus
  ports:
    - name: http    
      port: 9090
      nodePort: 30090
  type: NodePort