apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuma
  name: kuma-forum-api
  namespace: lab
spec:
  ports:
  - name: kuma-forum-api
    port: 3001
    protocol: TCP
    targetPort: 3001
  type: LoadBalancer
  selector:
    app: kuma  

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: kuma
#   name: kuma-forum-api
#   namespace: lab
# spec:
#   ports:
#   - name: kuma
#     nodePort: 30081
#     port: 3001
#     protocol: TCP
#     targetPort: 3001
#   selector:
#     app: kuma
#   type: NodePort    




# apiVersion: v1
# kind: Service
# metadata:
#     labels:
#       app: kuma
#     name: kuma-forum-api
#     namespace: lab
# spec:
#   type: ClusterIP
#   ports:
#   - name: kuma-forum-api
#     port: 3001
#     targetPort: 3001
#   selector:
#     app: kuma
#   sessionAffinity: None   
  