apiVersion: v1
kind: Service
metadata:
  name: kuma-forum-api
  namespace: lab
spec:
  ports:
  - name: kuma
    nodePort: 30080
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: kuma
  type: NodePort  