{
 "title": "dash-forum-api",
 "description": "dash-forum-api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{job=\"app-forum-api\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", job=\"$job\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HEAP USED",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=\"$instance\", area=\"heap\"}) * 100 / sum(jvm_memory_max_bytes{job=\"$job\",instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " NON HEAP USED",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=\"$instance\", area=\"nonheap\"}) * 100 / sum(jvm_memory_max_bytes{job=\"$job\",instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REQUESTS TOTAL/SEC",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "erro 500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "erro 400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "erro 404"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{job=\"$job\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{job=\"$job\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(http_server_requests_seconds_bucket{job=\"$job\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "70%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{job=\"$job\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{job=\"$job\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "API uptime",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB  CONNECT TIMEOUT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{job=\"$job\",instance=\"$instance\",pool=\"$pool\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 404",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"404\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri=\"/topicos\"}[1m]))",
     "legendFormat": "/topicos"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri=\"/topicos/{id}\"}[1m]))",
     "legendFormat": "/topicos/{id}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri=\"/auth\"}[1m]))",
     "legendFormat": "/auth"
    }
   ]
  },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "hora da inicializacao",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\",instance=\"$instance\"} * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "POOL de conecxao jdbc",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{job=\"$job\", instance=\"$instance\",pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "description": "warnnigs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{job=\"$job\", instance=\"$instance\", level=\"warn\"}[5m])",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "increase(logback_events_total{job=\"$job\", instance=\"$instance\", level=\"error\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\",instance=\"$instance\", status=\"200\", uri=\"/topicos\"} [1m]) / rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", status=\"200\", uri=\"/topicos\"} [1m])",
     "legendFormat": "{{uri}}{{method}} {{status)}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\",instance=\"$instance\", status=\"200\", uri=\"/topicos/{id}\"} [1m]) / rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", status=\"200\", uri=\"/topicos/{id}\"} [1m])",
     "legendFormat": "{{uri}}{{method}} {{status)}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\",instance=\"$instance\", status=\"200\", uri=\"/auth\"} [1m]) / rate(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\", status=\"200\", uri=\"/auth\"} [1m])",
     "legendFormat": "{{uri}}{{method}} {{status)}"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$job\",instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_max{job=\"$job\",instance=\"$instance\", status=\"200\",uri=\"/topicos\"}[1m])",
     "legendFormat": "{{uri}}{{method}} {{status)}"
    }
   ]
  },
  {
   "title": "CONNECT STATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=\"$job\",instance=\"$instance\",pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{job=\"$job\",instance=\"$instance\",pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"$job\",instance=\"$instance\",pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  }
 ]
}