apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: lab
spec:
  ports:
  - name: grafana-forum-api
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer  
  selector:
    app: grafana
  