apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-forum-api
  namespace: lab
spec:    
  ports:
  - name: app-forum-api
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: app     