apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-forum-api
  namespace: lab
spec:
  type: ClusterIP
  ports:
  - name: app-forum-api
    port: 8080
    targetPort: 8080
  selector:
    app: app
    