apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client-forum-api
  namespace: lab
spec:
  type: ClusterIP
  ports:
  - name: client-forum-api
    port: 8080
    targetPort: 8080
  selector:
    app: client
    