apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-forum-api
  namespace: lab
spec:
  type: ClusterIP
  ports:
  - name: redis-forum-api
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  