apiVersion: v1
kind: Service
metadata:
  name: adminer-forum-api
  namespace: lab
spec:
  ports:
  - name: adminer-forum-api
    port: 8006
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: adminer  