apiVersion: v1
kind: Service
metadata:
  name: adminer-forum-api
  namespace: lab
spec:
  selector:
    app: adminer
  ports:
    - name: http    
      port: 8080
      nodePort: 30080
  type: NodePort