apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-forum-api
  namespace: lab
spec:
  type: ClusterIP
  ports:
  - name: mysql-forum-api
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  